# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Seascape Sport Horses - Gilroy, CA - Hunter/Jumper Training & Lessons
email: seascapesporthorses@gmail.com
author: Charis Dankert & Shannon Wilson
description: >
  Seascape Sport Horses specializes in importing high-end hunter, jumper, and equitation horses for the Santa Cruz area. Offering elite horseback riding lessons for all levels. Located in Bonny Doon CA.
copyright: Copyright &copy; 2017 Seascape Sport Horses. All Rights Reserved.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
